name: {{cookiecutter.package_name}}

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytest
  - flake8
  - rope
  - autopep8
  - click
  - jupyter
  - pyyaml
  - pytorch>=1.1.0
  - torchvision
  - cudatoolkit
  - tensorflow
  - tensorboard
  - absl-py
  - future
  - tqdm
  - mkdocs
  - pip
  - pyarrow
  - pyyaml
  - mypy
  - pip:
    - sklearn
    - dagster
    - dagit
    - -e .  # install package in development mode
